### ISSUE TITLE
COCO pretraining data error: "Image id cannot be found in image feature imageid_to_index file!"

### ISSUE THREAD

**Issue by ahnjaewoo** [microsoft/Oscar#106]
Hi,
I'm trying to pretrain Oscar (or Oscar+) model from scratch, but have some minor data problem :(
First, I'll share my yaml file for the dataset.
Of course, all of the files are downloaded from [https://github.com/microsoft/Oscar/blob/master/VinVL_MODEL_ZOO.md](url)
```
corpus: coco_flickr30k_gqa
corpus_file: coco_flickr30k_gqa.tsv
image_label_path:
  coco: image_labels/X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/coco
  flickr30k: image_labels/X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/flickr30k
  gqa: image_labels/X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/gqa
image_feature_path:
  coco: image_features/coco_X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/model_0060000
  flickr30k: image_features/flickr30k_X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/model_0060000
  gqa: image_features/gqa_X152C4_frcnnbig2_exp168model_0060000model.roi_heads.nm_filter_2_model.roi_heads.score_thresh_0.2/model_0060000
```
While I tried to start the code, an image id from `coco_flickr30k_gqa.tsv` isn't mapped with `imageid2idx.json` file in coco image feature directory. (Error from [https://github.com/microsoft/Oscar/blob/423997b099650914a37203110a244e2de0426c69/oscar/datasets/oscar_tsv.py#L117](url))

I think it's a bit strange, cause I didn't change any code. Is this just the problem of downloaded data or not?
Thanks.
